# Generated by Django 5.2.6 on 2025-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('manager', 'Hiring Manager')], default='Admin', max_length=20),
            preserve_default=False,
        ),
    ]
