# Generated by Django 5.2.6 on 2025-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter_name',
            field=models.CharField(default='Admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
